services:
  app:
    build: .
    image: resuminatore-app
    command: pnpm run start:dev:fast
    env_file: .env
    ports:
      - '3000:3000'
    networks:
      - resuminatore-network

  ai:
    build: .
    image: ai-service
    command: 'pnpm run start:dev:fast ai-service'
    env_file: .env
    ports:
      - '3001:3001'
    networks:
      - resuminatore-network

  # redis:
  #   image: redis:7-alpine
  #   command: ['redis-server', '--requirepass', 'admin']
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - resuminatore-redis-volume:/data
  #   networks:
  #     - resuminatore-network

# volumes:
#   resuminatore-redis-volume:

networks:
  resuminatore-network:
    driver: bridge
