import { TemplateType } from '@app/shared';

export const INITIAL_TEMPLATES: Partial<TemplateType>[] = [
  {
    name: 'Professional Elite',
    description: 'Sophisticated left sidebar design with elegant typography.',
    category: 'classic',
    thumbnailUrl: '/templates/thumbnails/professional-elite.png',
    isPremium: false,
    styles: {
      primaryColor: '#1a2332',
      secondaryColor: '#2d3e50',
      accentColor: '#3b82f6',
      fontFamily: "'Georgia', 'Garamond', serif",
      headingFont: "'Calibri', 'Arial', sans-serif",
      layout: 'sidebar-left',
      sidebarWidth: '35%',
      spacing: 'normal',
    },
    sampleData: {},
    htmlStructure:
      '<div class="resume-container">Professional Elite Structure</div>',
    cssStyles: '.resume { font-family: Georgia; }',
  },
  {
    name: 'Modern Executive',
    description: 'Premium two-column design with contemporary aesthetics.',
    category: 'modern',
    thumbnailUrl: '/templates/thumbnails/modern-executive.png',
    isPremium: true,
    styles: {
      primaryColor: '#0f172a',
      secondaryColor: '#1e293b',
      accentColor: '#8b5cf6',
      fontFamily: "'Roboto', 'Lato', sans-serif",
      headingFont: "'Helvetica', 'Arial', sans-serif",
      layout: 'two-column',
      sidebarWidth: '40%',
      spacing: 'relaxed',
    },
    sampleData: {},
    htmlStructure:
      '<div class="resume-container">Modern Executive Structure</div>',
    cssStyles: '.resume { font-family: Roboto; }',
  },
  {
    name: 'Creative Bold',
    description: 'Eye-catching right sidebar layout with vibrant accents.',
    category: 'creative',
    thumbnailUrl: '/templates/thumbnails/creative-bold.png',
    isPremium: false,
    styles: {
      primaryColor: '#1e1b4b',
      secondaryColor: '#312e81',
      accentColor: '#ec4899',
      fontFamily: "'Open Sans', sans-serif",
      headingFont: "'Montserrat', sans-serif",
      layout: 'sidebar-right',
      sidebarWidth: '38%',
      spacing: 'normal',
    },
    sampleData: {},
    htmlStructure:
      '<div class="resume-container">Creative Bold Structure</div>',
    cssStyles: '.resume { font-family: Open Sans; }',
  },
  {
    name: 'Technical Pro',
    description: 'Clean two-column technical layout optimized for developers.',
    category: 'modern',
    thumbnailUrl: '/templates/thumbnails/technical-pro.png',
    isPremium: false,
    styles: {
      primaryColor: '#0c4a6e',
      secondaryColor: '#075985',
      accentColor: '#06b6d4',
      fontFamily: "'Helvetica', 'Arial', sans-serif",
      headingFont: "'Roboto', 'Calibri', sans-serif",
      layout: 'two-column',
      sidebarWidth: '35%',
      spacing: 'compact',
    },
    sampleData: {},
    htmlStructure:
      '<div class="resume-container">Technical Pro Structure</div>',
    cssStyles: '.resume { font-family: Helvetica; }',
  },
  {
    name: 'Classic Elegant',
    description:
      'Timeless design with traditional typography. Perfect for consulting and law.',
    category: 'classic',
    thumbnailUrl: '/templates/thumbnails/classic-elegant.png',
    isPremium: true,
    styles: {
      primaryColor: '#1c1917',
      secondaryColor: '#44403c',
      accentColor: '#92400e',
      fontFamily: "'Times New Roman', 'Georgia', serif",
      headingFont: "'Arial', 'Helvetica', sans-serif",
      layout: 'sidebar-left',
      sidebarWidth: '33%',
      spacing: 'relaxed',
    },
    sampleData: {},
    htmlStructure:
      '<div class="resume-container">Classic Elegant Structure</div>',
    cssStyles: '.resume { font-family: "Times New Roman"; }',
  },
  {
    name: 'Classic Professional',
    description:
      'Clean and straightforward professional layout suitable for all industries.',
    category: 'classic',
    thumbnailUrl: '/templates/thumbnails/classic-professional.png',
    isPremium: false,
    styles: {
      primaryColor: '#27272a',
      secondaryColor: '#52525b',
      accentColor: '#0ea5e9',
      fontFamily: "'Arial', 'Helvetica', sans-serif",
      headingFont: "'Roboto', sans-serif",
      layout: 'single-column', // Guessing single column for a 'classic professional' feel
      sidebarWidth: '0%',
      spacing: 'normal',
    },
    sampleData: {},
    htmlStructure:
      '<div class="resume-container">Classic Professional Structure</div>',
    cssStyles: '.resume { font-family: Arial; }',
  },
];
